### PR TITLE
Fix build error, support torch DDP on OD train.py

### PR DESCRIPTION
**Pull request by alexh-deeplite**
This PR addresses two issues with the zoo

### Broken Build
The mim install was failing but manually adding the "mim" extra to the package description fixes the error
 
### Slow Object Detection Training:
Enables DistributedDataParallel (DDP) training, as opposed to DataParallel training. DDP is recommended by pytorch and Ultralytics Yolov5

Usage:
```
torchrun --nproc_per_node=4 training_scripts/object_detection/train.py 
```

Behavior before this fix:
```UnboundLocalError: local variable 'nc' referenced before assignment
Traceback (most recent call last):
  File "training_scripts/object_detection/train.py", line 426, in <module>
    main(opt)
  File "training_scripts/object_detection/train.py", line 413, in main
    train(opt, device)
  File "training_scripts/object_detection/train.py", line 111, in train
    num_classes=nc,
UnboundLocalError: local variable 'nc' referenced before assignment
```

There was also an issue with CPU usage during single GPU object detection training that caused a 3x increase in training time. I resolved this issue by setting the environment variable `OMP_NUM_THREADS=1` to reduce unnecessary CPU multithreading

### CODE REVIEW

**Comment by alexh-deeplite** [comment]
Please review the mmyolo PR #392 first so we can merge those changes to this branch and get passing tests on Travis once again

**Comment by alexh-deeplite** [comment]
cancelled the other PR due to needing an alternative solution, so let's review this PR @honnesh-deeplite @matteog11 @ravishk007

**Comment by ehsab** [comment]
> Added a couple lines to object_detection/train.py to resolve CPU performance issues during both single and multi-GPU training.
> 
> * Single GPU: Automatically set environment variable `OMP_NUM_THREADS=1` to prevent CPU bottleneck
>   
>   * Result: YOLO5n COCO 640px training epoch: from ~30 mins to 10 mins, **3x speedup**
> * Multi-GPU: Turn off multithreading for `cv2` package because it conflicts with torch dataloading threading
>   
>   * Result: YOLO5n COCO 640px training epoch: ~10 mins to 3 mins, **3.3x speedup**

interesting, how to turn it off?

**Review by honnesh-deeplite — APPROVED** [review]

**Review by ravishk007 — APPROVED** [review]
Looking good

**Review by matteog11 — APPROVED** [review]

**Comment by alexh-deeplite** [comment]
> > Added a couple lines to object_detection/train.py to resolve CPU performance issues during both single and multi-GPU training.
> > 
> > * Single GPU: Automatically set environment variable `OMP_NUM_THREADS=1` to prevent CPU bottleneck
> >   
> >   * Result: YOLO5n COCO 640px training epoch: from ~30 mins to 10 mins, **3x speedup**
> > * Multi-GPU: Turn off multithreading for `cv2` package because it conflicts with torch dataloading threading
> >   
> >   * Result: YOLO5n COCO 640px training epoch: ~10 mins to 3 mins, **3.3x speedup**
> 
> interesting, how to turn it off?

Turning off will require the user to modify the train script. It's definitely not recommended to turn off these enhancements since they speed up training

**Pull request merged**
